export { indexRepo } from './indexer.js';
export type { IndexOptions, IndexResult } from './indexer.js';
export { detectLanguage, grammarFor, allGrammars, isSupported } from './languages.js';
export type { GrammarInfo, TagsDialect } from './languages.js';
export { initParser, loadGrammar, parseSource, compileQuery } from './parser.js';
export { extractFile } from './extraction.js';
export type { FileExtraction, ExtractedSymbol, ExtractedRef, ExtractedImport, ExtractedRoute } from './extraction.js';
export { detectFileRoutes } from './file-routes.js';
export { ingestSecondBrain, resolveSecondBrainDir, stripFrontmatter } from './second-brain.js';
export type { IngestSecondBrainOptions, IngestSecondBrainResult } from './second-brain.js';
export { ingestAgentMemory, resolveAgentMemoryDir, isAgentMemoryFile } from './agent-memory.js';
export type { IngestAgentMemoryOptions, IngestAgentMemoryResult } from './agent-memory.js';
export { generateBrainCards, ingestGeneratedBrain } from './second-brain-gen.js';
export type { BrainLevel, GenerateBrainOptions, GeneratedCard, GenerateBrainResult } from './second-brain-gen.js';
export { checkStaleness, extractCodeRefs, refIsAlive, checkableRef, isOurRepoRef } from './staleness.js';
export type { StalenessResult } from './staleness.js';
export { buildNoteCodeEdges } from './note-code-links.js';
export type { NoteCodeLinkResult } from './note-code-links.js';
export { generateWiki, writeWiki, renderWikiHtml, wikiDirIsOurs, WikiDirNotOursError, WIKI_MARKER } from './wiki-gen.js';
export type { WikiFile, GenerateWikiOptions } from './wiki-gen.js';
export { Ignorer } from './ignore.js';
export { walk } from './walk.js';
export { hashContent } from './hash.js';
export * as git from './git.js';
